default['weblogic']['owner'] = 'oracle'
default['weblogic']['user'] = 'oracle'
default['weblogic']['group'] = 'oinstall'
default['weblogic']['mw_home'] = '/u01/app/oracle/product/fmw12.2.1'
default['weblogic']['install_type'] = 'Fusion Middleware Infrastructure With Examples'
default['weblogic']['response_file'] = '/root/install_weblogic.rsp'
default['weblogic']['install_image'] = '/vagrant_data/wls1221/fmw_12.2.1.0.0_infrastructure.jar'
